-- Setup Relational Tables for POS Module

-- Create orders table
CREATE TABLE IF NOT EXISTS public.orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venda uuid DEFAULT gen_random_uuid() NOT NULL,
    nome_cliente text NOT NULL,
    instagram text,
    total numeric(10,2) NOT NULL DEFAULT 0,
    forma_de_pagamento text NOT NULL, -- 'Dinheiro', 'Pix', 'Cartão'
    status text NOT NULL DEFAULT 'Concluída',
    sales_channel text NOT NULL DEFAULT 'pos',
    data_venda timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create order_items table
CREATE TABLE IF NOT EXISTS public.order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint REFERENCES public.orders(id) ON DELETE CASCADE,
    product_ref text NOT NULL,
    nome_artigo text NOT NULL,
    quantidade integer NOT NULL CHECK (quantidade > 0),
    preco_unitario numeric(10,2) NOT NULL,
    lucro_unitario numeric(10,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (Row Level Security) and Policies
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public access for orders" ON public.orders FOR ALL USING (true);
CREATE POLICY "Allow public access for order items" ON public.order_items FOR ALL USING (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_orders_data_venda ON public.orders(data_venda DESC);
CREATE INDEX IF NOT EXISTS idx_orders_sales_channel ON public.orders(sales_channel);
CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON public.order_items(order_id);
