-- ============================================================
-- Migração das tabelas existentes para multi-tenant
-- Corra no Supabase SQL Editor DEPOIS de supabase_saas_migration.sql
-- ============================================================

-- 1. loja_app_state — adicionar store_id
ALTER TABLE public.loja_app_state
  ADD COLUMN IF NOT EXISTS store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS idx_loja_app_state_store
  ON public.loja_app_state(store_id);

-- RLS
ALTER TABLE public.loja_app_state ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "app_state: member CRUD" ON public.loja_app_state;

CREATE POLICY "app_state: member CRUD" ON public.loja_app_state
  FOR ALL USING (
    store_id = public.my_store_id()
    OR store_id IS NULL  -- backwards compat: rows sem store_id ficam acessíveis
  );

-- 2. loja_compras — adicionar store_id
ALTER TABLE public.loja_compras_legacy
  ADD COLUMN IF NOT EXISTS store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE;

-- Criar versão nova (limpa) de loja_compras com store_id obrigatório
CREATE TABLE IF NOT EXISTS public.loja_compras (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  store_id     uuid NOT NULL REFERENCES public.stores(id) ON DELETE CASCADE,
  ref          text NOT NULL,
  data_compra  date NOT NULL DEFAULT current_date,
  quantidade   integer NOT NULL CHECK (quantidade > 0),
  preco_custo  numeric,
  fornecedor   text,
  notas        text,
  size         text,
  color        text,
  created_at   timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_loja_compras_store ON public.loja_compras(store_id);
CREATE INDEX IF NOT EXISTS idx_loja_compras_ref   ON public.loja_compras(ref);

ALTER TABLE public.loja_compras ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "compras: member CRUD" ON public.loja_compras;

CREATE POLICY "compras: member CRUD" ON public.loja_compras
  FOR ALL USING (store_id = public.my_store_id());

-- 3. live_sessions — adicionar store_id
DO $$ BEGIN
  IF EXISTS (SELECT FROM pg_tables WHERE schemaname='public' AND tablename='live_sessions') THEN
    ALTER TABLE public.live_sessions
      ADD COLUMN IF NOT EXISTS store_id uuid REFERENCES public.stores(id) ON DELETE CASCADE;

    ALTER TABLE public.live_sessions ENABLE ROW LEVEL SECURITY;
  END IF;
END $$;

DROP POLICY IF EXISTS "live_sessions: member CRUD" ON public.live_sessions;
CREATE POLICY "live_sessions: member CRUD" ON public.live_sessions
  FOR ALL USING (
    store_id = public.my_store_id()
    OR store_id IS NULL
  );

-- 4. Verificação
SELECT tablename, rowsecurity
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN ('loja_app_state', 'loja_compras', 'live_sessions')
ORDER BY tablename;
