-- Create a table for Manual Purchases (Inflows)
create table loja_compras (
  id bigint generated by default as identity primary key,
  ref text not null, -- Links to Base de Itens
  data_compra date not null default current_date,
  quantidade integer not null check (quantidade > 0),
  preco_custo numeric, -- Optional: Cost price for valuation
  fornecedor text,
  notas text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS (Row Level Security) if needed, or allow public access for now based on current project setup
alter table loja_compras enable row level security;

-- Policy to allow authenticated users (and anon if configured that way) to read/write
create policy "Allow public access" on loja_compras for all using (true);

-- Create an index on 'ref' for faster lookups
create index idx_loja_compras_ref on loja_compras(ref);
